version: '3.8'

services:
  sadp-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/sadp
    depends_on:
      - redis
      - postgres
    networks:
      - sadp-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sadp-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=sadp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sadp-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - sadp-api
    networks:
      - sadp-network

volumes:
  redis_data:
  postgres_data:

networks:
  sadp-network:
    driver: bridge
